resilience4j:
  circuitbreaker:
    configs:
      custom:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
    instances:
      items:
        base-config: custom
  timelimiter:
    configs:
      custom:
        timeout-duration: 6s
    instances:
      items:
        base-config: custom